#!/usr/bin/env bash

set -e
SCRIPT_DIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
source "$SCRIPT_DIR/dir"

DOCKER_MOUNTS="$DEV_DIR/docker_mounts"

echo "Creating docker images"
mkdir -p "$DOCKER_MOUNTS"

echo "Starting Docker environment with docker compose"
cd "$DEV_DIR"
docker compose -f docker-compose.yml start