version: '3.8'
services:
  db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_PASSWORD: test1234
      POSTGRES_USER: hygge
      POSTGRES_DB: hygge
    ports:
      - "5433:5432"
    volumes:
      - ./docker_mounts/db:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    restart: always
    command: "redis-server --save 20 1 --loglevel warning"
    ports:
      - "6380:6379"
    volumes:
      - ./docker_mounts/redis:/data