version: '3.8'
services:
  db:
    image: postgres:15.2-alpine
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./docker_mounts/db:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    restart: always
    command: "redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./docker_mounts/redis:/data