#!/usr/bin/env bash

set -e
SCRIPT_DIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
source "$SCRIPT_DIR/dir"

test_for () {
  echo -n "Testing for \"$@\" ... "
  $($@ &> /dev/null) && echo "✓" || echo "✗"
}

echo "Installing git-hooks"
rm -rf "$GIT_DIR/hooks"
ln -s "$DEV_DIR/git_hooks/" "$GIT_DIR/hooks"

test_for docker compose version
test_for cargo sqlx -V
test_for drill -V
test_for hurl -V