name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Format
        run: cargo fmt --all --check
      - name: Check
        run: cargo check
      - name: Build
        run: cargo build --verbose